export enum EDevProfileSections {
  ContactInfo,
  ProfileSettings,
  CategoriesAndSkills,
  WorkExperience,
  ActiveProjects,
  WantToLearn,
  Certificates,
  Balance,
  PasswordAndSecurity,
  BillingAndPayments,
  Education,
  SoftSkills,
  ApprovedProjects,
  Reviews,
  Employment,
  Languages,
  HourlyRate
}
