export enum EDevProfileSections {
  CategoriesAndSkills,
  WorkExperience,
  ActiveProjects,
  WantToLearn,
  Certificates,
  Balance,
  PasswordAndSecurity,
  BillingAndPayments,
  Education,
  SoftSkills,
  ApprovedProjects,
  Reviews,
  Employment,
  Languages,
  HourlyRate,
  AccountInfo,
  LocationInfo
}
